### ISSUE TITLE
Cleaning destination repository of old files leaves .github directory and .gitattributes file

### ISSUE THREAD

**Issue by ruudk** [cpina/github-action-push-to-another-repository#16]
It's related to this line:
https://github.com/cpina/github-action-push-to-another-repository/blob/976916018a4108195b74a5663a045141c6708c79/entrypoint.sh#L31

Because the directory `.github` starts with `.git` it's skipped. Same for file `.gitattributes`.

I tried `grep -v "^$CLONE_DIR/\.git$"` but that didn't work.

**Comment by cpina** [comment]
> It's related to this line:
> 
> https://github.com/cpina/github-action-push-to-another-repository/blob/976916018a4108195b74a5663a045141c6708c79/entrypoint.sh#L31
> 
> Because the directory `.github` starts with `.git` it's skipped. Same for file `.gitattributes`.

Oops, I'll fix this

> I tried `grep -v "^$CLONE_DIR/\.git$"` but that didn't work.

Did you mean "that did work"? Becasue I'm checking it locally and it works:
```
carles@pinux:~$ find test | grep -v "^test\/.git$" | grep -v "^test$"
test/readme.md
test/cookies.txt
test/readme.pdf
test/.gitattributes
test/to_delete
test/.github
test/readme.html
test/readme.txt
test/test.lyx~
carles@pinux:~$ 
```

If you confirm that this worked for you (I think so for what I see in your repository) I'll make the change in this repo.

Thanks!

**Comment by ruudk** [comment]
No, it didn't work. On macOS in bash it works. But since this is running in `bin/sh` you might want to try it there.

**Comment by ruudk** [comment]
See https://github.com/LongRunning/LongRunning/runs/1486470971?check_suite_focus=true

It uses TomasVotruba/github-action-monorepo-split@cedf23162acafcf5fb036d911606a33318dc5f87 
that is based on this repo.

**Comment by cpina** [comment]
> No, it didn't work. On macOS in bash it works. But since this is running in `bin/sh` you might want to try it there.

I've just tried locally with a Busybox environment (it might depend on the version of grep and find*) and it was working for me.

I'll give it a try in the action itself, thanks for the ilnks.

*: e.g.:
```
/ # grep 
BusyBox v1.31.1 () multi-call binary.
```

Either way, I'll try in the GitHub Action :-)

**Comment by cpina** [comment]
While testing the fix that we discussed above I had a different problem: $CLONE_DIR/.git was not removed but files like $CLONE_DIR/.git/HEAD were removed.

I've pushed to https://github.com/cpina/github-action-push-to-another-repository/commit/ec672cbc0a61a428e1678d62a43fbeb8a6ea0154 a cleaner (I think) solution using only path and excluding paths instead of concatenating different "grep -v". Hopefully this would work for you, if it doesn't feel free to send a link to the log and I'll have another look.

**Comment by ruudk** [comment]
@cpina Wow, thanks! Gonna try it.

**Comment by ruudk** [comment]
Still getting issues here :( 

https://github.com/symplify/github-actions/runs/1488292885?check_suite_focus=true

https://github.com/symplify/github-actions/blob/master/packages/monorepo-split-github-action/entrypoint.sh#L50

**Comment by ruudk** [comment]
Found a way to reproduce it:
```
$ mkdir -p b/.git b/.github && touch b/.git/blaat b/.github/test b/other && ls -la b/ && export CLONE_DIR=(pwd)/b
total 0
drwxr-xr-x  5 Ruud  staff  160 Dec  2 20:06 ./
drwxr-xr-x  4 Ruud  staff  128 Dec  2 20:06 ../
drwxr-xr-x  3 Ruud  staff   96 Dec  2 20:06 .git/
drwxr-xr-x  3 Ruud  staff   96 Dec  2 20:06 .github/
-rw-r--r--  1 Ruud  staff    0 Dec  2 20:06 other
```

Then run:
```
find "$CLONE_DIR" ! -path "$CLONE_DIR" ! -path "$CLONE_DIR/.git/*"  ! -path "$CLONE_DIR/.git"  -exec rm -rf {} \;
find: /Users/Ruud/Downloads/test/b/.github: No such file or directory
```

**Comment by cpina** [comment]
> Still getting issues here :(
> 
> https://github.com/symplify/github-actions/runs/1488292885?check_suite_focus=true
> 
> https://github.com/symplify/github-actions/blob/master/packages/monorepo-split-github-action/entrypoint.sh#L50

Oh! I have an idea of what could the problem be. I'll check later today and let you know

**Comment by ruudk** [comment]
I'm trying a different approach that seems much simpler, maybe you can use it as well: https://github.com/symplify/github-actions/pull/12

**Comment by cpina** [comment]
I think that I'll use your approach. I had thought of this long time ago and I thought that "deleting it is equally simple" and I don't think this anymore!

**Comment by cpina** [comment]
@ruudk : I've pushed to `master` the `mv` approach and tested. Thanks for the feedback!

**Comment by ruudk** [comment]
@cpina Great Thanks for helping me out, much appreciated 🙌
